/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AnneeScolaire } from './anneeScolaire';
import { Niveau } from './niveau';
import { Periode } from './periode';
import { Professeur } from './professeur';
import { Etablissement } from './etablissement';


export interface EtablissementProfesseur { 
    idEtablissementProfesseur?: number;
    professeur?: Professeur;
    etablissement?: Etablissement;
    anneeScolaire?: AnneeScolaire;
    niveaux?: Set<Niveau>;
    periodes?: Set<Periode>;
}

