/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Classe } from './classe';
import { EtablissementProfesseur } from './etablissementProfesseur';


export interface Niveau { 
    idNiveau?: number;
    libelle?: string;
    etablissementProfesseur?: EtablissementProfesseur;
    classes?: Set<Classe>;
}

