/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LocalTime } from './localTime';
import { DevoirDto } from './devoirDto';
import { EleveDto } from './eleveDto';


export interface EleveDevoirDto { 
    idEleveDevoir?: number;
    eleve?: EleveDto;
    devoir?: DevoirDto;
    datePassage?: string;
    heurePassage?: LocalTime;
    note?: number;
}

