export * from './absence.service';
import { AbsenceService } from './absence.service';
export * from './anneeScolaire.service';
import { AnneeScolaireService } from './anneeScolaire.service';
export * from './authController.service';
import { AuthControllerService } from './authController.service';
export * from './classe.service';
import { ClasseService } from './classe.service';
export * from './classeEleve.service';
import { ClasseEleveService } from './classeEleve.service';
export * from './contenu.service';
import { ContenuService } from './contenu.service';
export * from './devoir.service';
import { DevoirService } from './devoir.service';
export * from './devoirEleve.service';
import { DevoirEleveService } from './devoirEleve.service';
export * from './eleve.service';
import { EleveService } from './eleve.service';
export * from './etablissement.service';
import { EtablissementService } from './etablissement.service';
export * from './etablissementProfesseur.service';
import { EtablissementProfesseurService } from './etablissementProfesseur.service';
export * from './niveau.service';
import { NiveauService } from './niveau.service';
export * from './periode.service';
import { PeriodeService } from './periode.service';
export * from './professeur.service';
import { ProfesseurService } from './professeur.service';
export * from './role.service';
import { RoleService } from './role.service';
export * from './seance.service';
import { SeanceService } from './seance.service';
export * from './utilisateur.service';
import { UtilisateurService } from './utilisateur.service';
export const APIS = [AbsenceService, AnneeScolaireService, AuthControllerService, ClasseService, ClasseEleveService, ContenuService, DevoirService, DevoirEleveService, EleveService, EtablissementService, EtablissementProfesseurService, NiveauService, PeriodeService, ProfesseurService, RoleService, SeanceService, UtilisateurService];
