/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LocalTime } from './localTime';
import { PeriodeDto } from './periodeDto';
import { EleveDto } from './eleveDto';


export interface AbsenceDto { 
    idAbsence?: number;
    eleve?: EleveDto;
    date?: string;
    heure?: LocalTime;
    motif?: string;
    periode?: PeriodeDto;
}

