/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PeriodeDto } from './periodeDto';


export interface DevoirDto { 
    idDevoir?: number;
    libelle?: string;
    type?: DevoirDto.TypeEnum;
    coefficient?: number;
    periode?: PeriodeDto;
}
export namespace DevoirDto {
    export type TypeEnum = 'Control' | 'Activity';
    export const TypeEnum = {
        Control: 'Control' as TypeEnum,
        Activity: 'Activity' as TypeEnum
    };
}


