/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RoleDto } from './roleDto';


export interface UtilisateurDto { 
    id?: number;
    nom?: string;
    prenom?: string;
    email?: string;
    dateDeNaissance?: string;
    photo?: string;
    roles?: Array<RoleDto>;
    professeurNom?: string;
    professeurPrenom?: string;
    motDePasse?: string;
}

