/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SousClasseDto } from './sousClasseDto';
import { LocalTime } from './localTime';
import { ProfesseurDto } from './professeurDto';
import { ClasseDto } from './classeDto';


export interface SeanceDto { 
    idSeance?: number;
    professeur?: ProfesseurDto;
    classe?: ClasseDto;
    sousClasse?: SousClasseDto;
    typeSeance?: string;
    jour?: SeanceDto.JourEnum;
    heureDebut?: LocalTime;
    heureFin?: LocalTime;
}
export namespace SeanceDto {
    export type JourEnum = 'MONDAY' | 'TUESDAY' | 'WEDNESDAY' | 'THURSDAY' | 'FRIDAY' | 'SATURDAY' | 'SUNDAY';
    export const JourEnum = {
        Monday: 'MONDAY' as JourEnum,
        Tuesday: 'TUESDAY' as JourEnum,
        Wednesday: 'WEDNESDAY' as JourEnum,
        Thursday: 'THURSDAY' as JourEnum,
        Friday: 'FRIDAY' as JourEnum,
        Saturday: 'SATURDAY' as JourEnum,
        Sunday: 'SUNDAY' as JourEnum
    };
}


