/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Utilisateur { 
    idUtilisateur?: number;
    nom?: string;
    prenom?: string;
    email?: string;
    dateDeNaissance?: string;
    motDePasse?: string;
    photo?: string;
}

